# Generated by Django 5.0.3 on 2024-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trees_json",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_tree", models.CharField(max_length=30, verbose_name="Название")),
                ("breed", models.CharField(max_length=50, verbose_name="Порода")),
                ("age", models.IntegerField(verbose_name="Возраст")),
                ("diameter", models.IntegerField(verbose_name="Диаметр")),
                ("height", models.IntegerField(verbose_name="Высота")),
                ("coordinate_X", models.IntegerField(verbose_name="Координата_X")),
                ("coordinate_Y", models.IntegerField(verbose_name="Координата_Y")),
            ],
            options={
                "verbose_name": "Дерево",
                "verbose_name_plural": "Деревья",
                "db_table": "trees_json",
                "managed": True,
            },
        ),
    ]
