# Generated by Django 5.0.3 on 2024-04-08 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_folder",
                    models.CharField(max_length=30, verbose_name="Название_папки"),
                ),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
                "db_table": "folders",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="trees_json",
            name="folder_pk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.folders",
            ),
        ),
    ]
