# Generated by Django 5.0.3 on 2024-05-23 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_folders_name_folder_eng"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folders",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Владелец",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="folders",
            name="shared",
            field=models.ManyToManyField(
                blank=True, related_name="Другие_владельцы", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
